CREATE TABLE [dbo].[MBA_CALIBLOAD] (
    [CALIBLOAD]        INT           IDENTITY (0, 1) NOT NULL,
    [MBANUM]           VARCHAR (20)  CONSTRAINT [DF__MBA_CALIB__MBANU__0C2B7AFB] DEFAULT ('') NOT NULL,
    [DOC]              INT           CONSTRAINT [DF__MBA_CALIBLO__DOC__0D1F9F34] DEFAULT ((0)) NOT NULL,
    [MBA_STATUSNAME]   VARCHAR (16)  CONSTRAINT [DF__MBA_CALIB__MBA_S__0E13C36D] DEFAULT ('') NOT NULL,
    [USERLOGIN]        VARCHAR (20)  CONSTRAINT [DF__MBA_CALIB__USERL__0F07E7A6] DEFAULT ('') NOT NULL,
    [STATCODE]         VARCHAR (2)   CONSTRAINT [DF__MBA_CALIB__STATC__0FFC0BDF] DEFAULT ('') NOT NULL,
    [CDATE]            INT           CONSTRAINT [DF__MBA_CALIB__CDATE__10F03018] DEFAULT ((0)) NOT NULL,
    [UDATE]            INT           CONSTRAINT [DF__MBA_CALIB__UDATE__11E45451] DEFAULT ((0)) NOT NULL,
    [FDATE]            INT           CONSTRAINT [DF__MBA_CALIB__FDATE__12D8788A] DEFAULT ((0)) NOT NULL,
    [LSTATCODE]        VARCHAR (2)   CONSTRAINT [DF__MBA_CALIB__LSTAT__13CC9CC3] DEFAULT ('') NOT NULL,
    [KLINE]            INT           CONSTRAINT [DF__MBA_CALIB__KLINE__14C0C0FC] DEFAULT ((0)) NOT NULL,
    [MBA_UPDTRPORTNUM] VARCHAR (8)   CONSTRAINT [DF__MBA_CALIB__MBA_U__732AC307] DEFAULT ('') NOT NULL,
    [UPDATEMABANUM]    VARCHAR (6)   CONSTRAINT [DF_MBA_CALIBLOAD_UPDATEMABANUM] DEFAULT ('') NULL,
    [MEMO]             VARCHAR (200) NULL,
    [COMPUTER_NAME]    VARCHAR (50)  NULL,
    [NEXTCALIBDATE]    INT           CONSTRAINT [DF_MBA_CALIBLOAD_NEXTCALIBDATE] DEFAULT ((0)) NOT NULL,
    [PARTMODEL]        VARCHAR (30)  CONSTRAINT [DF_MBA_CALIBLOAD_PARTMODEL] DEFAULT ('') NOT NULL,
    [MNFCTRNAME]       VARCHAR (32)  CONSTRAINT [DF_MBA_CALIBLOAD_MNFCTRNAME] DEFAULT ('') NOT NULL,
    [MNFCTRCODE]       VARCHAR (17)  CONSTRAINT [DF_MBA_CALIBLOAD_MNFCTRCODE] DEFAULT ('') NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [MBA_CALIBLOAD#2#DOC#KLINE]
    ON [dbo].[MBA_CALIBLOAD]([DOC] ASC, [KLINE] ASC);


GO
CREATE NONCLUSTERED INDEX [MBA_CALIBLOAD#1#CALIBLOAD]
    ON [dbo].[MBA_CALIBLOAD]([CALIBLOAD] ASC);

