CREATE TABLE [dbo].[Orders] (
    [ID]                   INT            IDENTITY (1, 1) NOT NULL,
    [OrderNumber]          NCHAR (12)     NOT NULL,
    [OpenDate]             DATETIME       NOT NULL,
    [CustomerId]           INT            NOT NULL,
    [CustomerName]         NVARCHAR (255) NULL,
    [CustomerPhone]        NVARCHAR (25)  NULL,
    [CustomerContactName]  NVARCHAR (50)  NULL,
    [CustomerCity]         NVARCHAR (50)  NULL,
    [CustomerAddress]      NVARCHAR (255) NULL,
    [CustomerContactPhone] NVARCHAR (25)  NULL,
    [MBAContactName]       NVARCHAR (50)  NULL,
    [MBAContactPhone]      NVARCHAR (25)  NULL,
    [MBAContactMobile]     NVARCHAR (25)  NULL,
    [ClientRemarks]        NVARCHAR (MAX) NULL,
    [MbaReportNumber]      NVARCHAR (20)  NULL,
    [SerialNumber]         NVARCHAR (20)  NULL,
    [ManufacturerNumber]   NVARCHAR (20)  NULL,
    [DeviceDescription]    NVARCHAR (50)  NULL,
    [DeviceModel]          NVARCHAR (30)  NULL,
    [CalibDate]            DATETIME       NULL,
    [NextCalibDate]        DATETIME       NULL,
    [CalibMonth]           INT            NULL,
    [ReturnDate]           DATETIME       NULL,
    [PartName]             NVARCHAR (25)  NULL,
    [PartDescription]      NVARCHAR (60)  NULL,
    [IsInHouse]            BIT            NULL,
    [DepartmentCode]       INT            NULL,
    [DepartmentName]       NVARCHAR (50)  NULL,
    [CalibStatusCode]      INT            NULL,
    [CalibStatus]          NVARCHAR (12)  NULL,
    [Device manufacturer]  NVARCHAR (255) NULL,
    [Klita]                NVARCHAR (20)  NULL,
    [IsCancelled]          BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Orders_1] PRIMARY KEY CLUSTERED ([ID] ASC)
);

