MERGE INTO [dbo].[Statuses] AS dest
USING (
	SELECT 
	  sc.StatusCategoryId
	 ,ds.[Code]
	 ,ds.[StatusDescriptionENG]
	 ,LTRIM(RTRIM(ds.[StatusDescriptionHEB])) AS [StatusDescriptionHEB]
	FROM (
		VALUES
		('ReportStatus','AA','Received',N'נקלט'),
		('ReportStatus','AC','OpeningNewCalibration',N'פתיחת כיול חדש'),
		('ReportStatus','DC','StandbyModeCustomerReason',N'מצב המתנה (סיבת לקוח)'),
		('ReportStatus','DM','StandbyModeImporterReason',N'מצב המתנה (סיבת מבא)'),
		('ReportStatus','FC','ContinueCalibrationAfterStandby',N'המשך כיול לאחר המתנה'),
		('ReportStatus','GR','CreateCalibrationReport',N'יצירת דוח כיול'),
		('ReportStatus','CD','CreateCalibrationReportForFirstTime',N'יצירת דוח כיול פעם ראשונה'),
		('ReportStatus','H1','FirstSignature',N'חתימה ראשונה'),
		('ReportStatus','H2','SecondSignature',N'חתימה שניה'),
		('ReportStatus','HR','ReportRejectedByApprover',N'דוח נדחה על ידי מאשר'),
		('ReportStatus','TX','DeviceSentToCustomer',N'מכשיר נשלח ללקוח'),
		('ReportStatus','UC','OpenReportForUpdate',N'פתיחת דוח לעדכון'),
		('ReportStatus','UM','UpdatedReportStandbyModeImporterReason',N'דוח עדכון מצב המתנה (סיבת מבא)'),
		('ReportStatus','UD','UpdatedReportStandbyModeCustomerReason',N'דוח עדכון מצב המתנה (סיבת לקוח)'),
		('ReportStatus','UF','UpdatedReportContinueCalibrationAfterStandby',N'דוח עדכון המשך כיול לאחר המתנה'),
		('ReportStatus','UG','CreateUpdatedReport',N'יצירת דוח עדכון'),
		('ReportStatus','UP','CreatePdfOfUpdatedReport',N'יצירת PDF של דוח העדכון'),
		('ReportStatus','UX','UpdatedReportSentToCustomer',N'נשלח דוח העדכון ללקוח'),
		('CalibrationStatuses','','WaitingForCalibration',N'מחכה לכיול'),
		('CalibrationStatuses','','InCalibration',N'בכיול'),
		('CalibrationStatuses','','CalibrationFailed',N'כיול נכשל'),
		('CalibrationStatuses','','Packaged',N'אריזה'),
		('CalibrationStatuses','','CalibrationSuccess',N'כיול הצליח'),
		('CalibrationStatuses','','Delivered',N'נשלח'),
		('CalibrationStatuses','','Stopped',N'הופסק'),
		('CalibrationStatuses','','Adjusted',N'כויל'),
		('CalibrationStatuses','','ReadyForDelivery',N'ממתין לאיסוף'),
		('CalibrationStatuses','','WaitingForPacking',N'ממתין לאריזה'),
		('CalibrationStatuses','','ReadyForPacking',N'מוכן לאריזה'),
		('CalibratedUnitsStatus','','Functional',N'תקין'),
		('CalibrationStatuses','','TestedMetTheStandard',N'נבדק עומד'),
		('CalibrationStatuses','','TestedDidn''tMeetTheStandards',N'נבדק - לא עומד'),
		('CalibrationStatuses','','CannotBeDetermined',N'לא ניתן לקבוע'),
		('CalibrationStatuses','','AwaitingComments',N'ממתין להערות'),
		('CalibrationStatuses','','AwaitingSignature',N'ממתין לחתימה'),
		('CalibrationStatuses','','AwaitingCalibration',N'ממתין לכיול'),
		('CalibrationStatuses','','Calibration',N'כיול'),
		('CalibratedUnitsStatus','','DamagedDoor Seal',N'אטם דלת פגום'),
		('CalibratedUnitsStatus','','BrokenHandle',N'ידית שבורה'),
		('CalibratedUnitsStatus','','FaultyDoor',N'דלת לא תקינה'),
		('CalibratedUnitsStatus','','FaultyFan',N'מאוור לא תקין'),
		('CalibratedUnitsStatus','','CrackInTheGlass',N'סדק בזכוכית'),
		('SpecialCare','','Packing',N'אריזה'),
		('SpecialCare','','CustomerComplaint',N'תלונת לקוח'),
		('SpecialCare','','Shared',N'משותף'),
		('SpecialCare','','Urgent',N'דחוף '),
		('CarStatus','','Available',N'תקין'),
		('CarStatus','','Treatment',N'טיפול'),
		('CarStatus','','UnAvailable',N'לא זמין'),
		('CarStatus','','Sold',N'נמכר'),
		('CalibrationEquipmentStatus','','Available',N'זמין '),
		('CalibrationEquipmentStatus','','Treatment',N'טיפול'),
		('CalibrationEquipmentStatus','','Damage',N'תקול '),
		('UserAvailabilityStatus','','Available',N'זמין '),
		('UserAvailabilityStatus','','Sick',N'חולה'),
		('UserAvailabilityStatus','','Vacation',N'חופשה'),
		('UserAvailabilityStatus','','Maba',N'מ.ב.א'),
		('UserAvailabilityStatus','','InActive',N'לא פעיל'),
		('MeasurementDeviceStatus','','Available',N'זמין '),
		('MeasurementDeviceStatus','','NotCalibrated',N'לא מכויל'),
		('MeasurementDeviceStatus','','Damaged',N'תקול'),
		('MeasurementDeviceStatus','','Lost',N'אבד'),
		('MeasurementDeviceStatus','','SentForCalibration',N'נשלח לכיול'),
		('OrderStatus','','Received',N'נקלט'),
		('OrderStatus','','Sent',N'נשלח'),
		('OrderStatus','','ReportGenerated',N'הופק דו"ח'),
		('OrderStatus','','Packed',N'נארז'),
		('OrderStatus', '', 'WaitingForValidation', N'ממתין לולידציה'),
		('OrderStatus', '', 'WaitingForDelivery', N'ממתין למשלוח'),
		('OrderStatus', '', 'AcceptedByCustomer', N'התקבל על ידי הלקוח'),
		('OrderStatus', '', 'Rejected', N'נדחה'),
		('OrderStatus', '', 'AwaitingConfirmation', N'ממתין לאישור'),
		('OrderStatus','', 'AwaitingCollection', N'ממתין לאיסוף '),
		('OrderStatus','', 'Finished', N'הסתיים '),
		('OrderStatus','','WaitingForCalibration',N'מחכה לכיול'),
		('EventTypes','','CompanyEventMandatory',N'אירוע חברה - חובה'),
		('EventTypes','','CompanyEventOptional',N' אירוע חברה -רשות'),
		('EventTypes','','SickLeave',N'מחלה'),
		('EventTypes','','Vacation',N'חופש'),
		('UserStatus','','Active',N'פעיל'),
		('UserStatus','','NotActive',N'לא פעיל'),
		('Position','CT','Calibration Technician',N'כייל'),
		('Position','TL','TeamLeader',N'ראש צוות'),
		('Position','DH','DepartmentHead',N'ראש מדור'),
		('Position','ME','MetrologyEngineer',N'טכנולוג'),
		('Position','COO','ChiefOperationsOfficer',N'מנהל תפעול'),
		('Position','CTO','ChiefTechnologyOfficer',N'מנהל טכני'),
		('ClientConfirmationStatus','','Pending',N'בהמתנה'),
		('ClientConfirmationStatus','','Confirmed',N'מאושר'),
		('ClientConfirmationStatus','','Rejected',N'נדחה'),
		('CalibratorNotificationType','','NewOrderNotification',N'הזמנה חדשה'),
		('CalibratorNotificationType','','DelayOrderNotification',N'הזמנה נדחתה'),
		('CalibratorNotificationType','','CancelOrderNotification',N'הזמנה בוטלה'),
		('CalibratorNotificationType','','ValidatorCommentNotification',N'הערת ביקורת'),
		('CalibratorNotificationType','','SecondSignatureNotification',N'חתימה שניה'),
		('StickerType','','Big',N'גדולה'),
		('StickerType','','Small',N'קטנה'),
		('StickerType','','Both',N'גדול וקטן'),
		('CalibrationCycleName','',N'Temperature',N'טמפרטורה'),
		('CalibrationCycleName','',N'Set Temperature',N'טמפרטורה מכוונת'),
		('CalibrationCycleName','',N'Temperature before adjustment',N'טמפרטורה לפני כיוונון'),
		('CalibrationCycleName','',N'Temperature after adjustment',N'טמפרטורה לאחר כיוונון'),
		('CalibrationCycleName','',N'Humidity',N'לחות'),
		('CalibrationCycleName','',N'Relative humidity ',N'לחות יחסית'),
		('CalibrationCycleName','',N'Set Humidity',N'לחות מכוונת'),
		('CalibrationCycleName','',N'Humidity before adjustment',N'לחות לפני כיוונון'),
		('CalibrationCycleName','',N'Humidity after adjustment',N'לחות אחרי כיוונון'),
		('CalibrationCycleName','',N'%CO2',N'%CO2'),
		('CalibrationCycleName','',N'Set %CO2',N'%CO2 מכוון'),
		('CalibrationCycleName','',N'%CO2 after adjustment',N'%CO2 לאחר כיוון'),
		('CalibrationCycleName','',N'%CO2 before adjustment',N'%CO2 לפני כיוון'),
		('CalibrationCycleName','',N'Pressure',N'לחץ'),
		('CalibrationCycleName','',N'Recovery time after power off',N'זמן התאוששות לאחר ניתוק חשמל'),
		('CalibrationCycleName','',N'Recovery Time after * minutes Power-off',N'זמן התאוששות לאחר ניתוק חשמל למשך * דקות'),
		('CalibrationCycleName','',N'Recovery Time after door opening',N'זמן התאוששות לאחר פתיחת דלת'),
		('CalibrationCycleName','',N'Recovery Time after * minutes door opening ',N'זמן התאוששות לאחר פתיחת דלת למשך * דקות'),
		('CalibrationCycleName','',N'Cycle  No. * with load',N'מחזור מס'' * עם מטען'),
		('CalibrationCycleName','',N'Cycle  No. * without load',N'מחזור מס'' * ללא מטען'),
		('CalibrationCycleName','',N'Pressure - Cycle No. * without load',N'לחץ - מחזור מס'' * ללא מטען'),
		('CalibrationCycleName','',N'Pressure - Cycle No * with load',N'לחץ - מחזור מס'' * עם מטען'),
		('CalibrationCycleName','',N'Cycle No. * with load - F0 calculation',N'מחזור מס'' * עם מטען - חישוב F0'),
		('CalibrationCycleName','',N'Cycle No. * without load - F0 calculation',N'מחזור מס'' * ללא מטען - חישוב F0'),
		('CalibrationCycleName','',N'Cycle No. * - F0 calculation',N'מחזור מס'' *- חישוב F0'),
		('CalibrationCycleName','',N'Set Value',N'ערך נבדק'),
		('CalibrationCycleName','',N'Refrigeration Chamber',N'תא קירור'),
		('CalibrationCycleName','',N'Freezing Chamber',N'תא הקפאה'),
		('CalibrationProcessDescription','',N'Tested by placing T/C sensors in the working zone (see attached sketch).',N'נבדק ע"י הצבת רגשי TC בחלל התא, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing a T/C sensor in the center of the working zone (see attached sketch).',N'נבדק ע"י הצבת רגש TC במרכז התא, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing T/C sensors and connecting a pressure transducer inside the working zone (see attached sketch).',N'נבדק ע"י הצבת רגשי TC וחיבור מתמר לחץ בחלל התא, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing a T/C sensor and connecting a pressure transducer at the center of the working zone (see attached sketch).',N'נבדק ע"י הצבת רגש TC וחיבור מתמר לחץ במרכז התא, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing T/C sensors in the working zone and a humidity sensor in the center of the zone (see attached sketch).',N'נבדק ע"י הצבת רגשי TC בחלל התא, ורגש לחות במרכז התא, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing humidity sensors in the working zone (see attached sketch).',N'נבדק ע"י הצבת רגשי לחות בחלל התא, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing a humidity sensor in the center of the working zone (see attached sketch). ',N'נבדק ע"י הצבת רגש לחות במרכז התא, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing a humidity sensor in a dedicated opening (see attached sketch). ',N'נבדק ע"י הצבת רגש לחות בפתח ייעודי, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing temperature and humidity sensors inside the working zone (see attached sketch).',N'נבדק ע"י הצבת רגשי טמפרטורה ולחות בחלל התא, ראה שרטוט מצורף'),
		('CalibrationProcessDescription','',N'Tested by placing PT100 sensors in the working zone (see attached sketch).',N'נבדק ע"י הצבת רגשי PT100 בחלל התא, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing a PT100 sensor in the center of the working zone (see attached sketch).',N'נבדק ע"י הצבת רגש PT100 במרכז התא, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing a CO2 sensor in the center of the working zone (see attached sketch).',N'נבדק ע"י הצבת רגש CO2 במרכז התא, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by sampling CO2 via extraction from the chamber.',N'נבדק ע"י דגימת CO2 באמצעות שאיבה מהתא.'),
		('CalibrationProcessDescription','',N'Tested by placing T/C sensors in the block''s bores (see attached sketch).',N'נבדק ע"י הצבת רגשי TC בקדחי הבלוק, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing a T/C sensor in the block''s bore (see attached sketch).',N'נבדק ע"י הצבת רגש TC בקדח הבלוק, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing wireless data loggers in the working zone (see attached sketch).',N'נבדק ע"י הצבת אוגרי נתונים אלחוטיים בחלל התא, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing a T/C sensor in a dedicated crucible, in the center of the furnace floor (see attached sketch).',N'נבדק ע"י הצבת רגש TC בכורית ייעודית, במרכז רצפת התנור, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing a master sensor in the bath.',N'נבדק ע"י הצבת רגש מסטר באמבט.'),
		('CalibrationProcessDescription','',N'Tested by moving the sensor throughout the bath volume.',N'נבדק ע"י הזזת רגש בנפח האמבט.'),
		('CalibrationProcessDescription','',N'Tested by placing a master sensor in the center of the working zone.',N'נבדק ע"י הצבת רגש מסטר במרכז התא.'),
		('CalibrationProcessDescription','',N'Tested by attaching T/C sensors to the chamber shelves (see attached sketch).',N'נבדק ע"י הצמדת רגשי TC למדפי התא, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by attaching a T/C sensor to the center of the chamber shelf (see attached sketch).',N'נבדק ע"י הצמדת רגש TC למדף התא במרכז, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by placing a master sensor approx. 10 mm above the nozzle (see attached sketch).',N'נבדק ע"י הצבת רגש מסטר כ - 10 מ"מ מעל הדיזה, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by attaching T/C sensors to the plate (see attached sketch).',N'נבדק ע"י הצמדת רגשי TC לפלטה, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by attaching a T/C sensor to the center of the plate (see attached sketch).',N'נבדק ע"י הצמדת רגש TC למרכז הפלטה, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by positioning a T/C sensor between the sealing jaws (see attached sketch).',N'נבדק ע"י הצבת רגש TC בין שפתי ההלחמה, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested by positioning T/C sensors between the sealing jaws (see attached sketch).',N'נבדק ע"י הצבת רגשי TC בין שפתי ההלחמה, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested using a surface sensor (see attached sketch).',N'נבדק ע"י רגש שטח, ראה שרטוט מצורף.'),
		('CalibrationProcessDescription','',N'Tested in a 6 mm bore only.',N'נבדק בקדח 6 מ"מ בלבד.'),
		('CalibrationProcessDescription','',N'Tested by attaching the soldering iron tip to a master sensor using solder.',N'נבדק ע"י הצמדת ראש המלחם לרגש מסטר עם בדיל.')
		) ds ([StatusCategory],[Code],[StatusDescriptionENG],[StatusDescriptionHEB])
		JOIN [dbo].[StatusesCategories] as sc ON ds.StatusCategory = sc.StatusDescriptionENG
	) AS source
	ON dest.[StatusDescriptionENG] = source.[StatusDescriptionENG]
	   AND dest.[StatusCategoryId] = source.[StatusCategoryId]
WHEN MATCHED
	THEN
		UPDATE
		SET  dest.[Code] = source.[Code]
			,dest.[StatusDescriptionENG] = source.[StatusDescriptionENG]
			,dest.[StatusDescriptionHEB] = source.[StatusDescriptionHEB]
WHEN NOT MATCHED BY TARGET
	THEN
		INSERT (
             [StatusCategoryId]
			,[Code]
			,[StatusDescriptionENG]
			,[StatusDescriptionHEB]
			)
		VALUES (
			source.[StatusCategoryId]
			,source.[Code]
			,source.[StatusDescriptionENG]
			,source.[StatusDescriptionHEB]
			);