//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertSetting
    {
        public int AlertCode { get; set; }
        public long DeviceID { get; set; }
        public bool IsEnable { get; set; }
        public bool IsSMSEnable { get; set; }
        public bool IsEmailEnable { get; set; }
    
        public virtual DeviceMain DeviceMain { get; set; }
    }
}
