//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigManager
    {
        public ConfigManager()
        {
            this.DeviceMain = new HashSet<DeviceMain>();
            this.ZoneMain1 = new HashSet<ZoneMain1>();
        }
    
        public long ConfigID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> SynDate { get; set; }
    
        public virtual ICollection<DeviceMain> DeviceMain { get; set; }
        public virtual Device_DisplaySettings Device_DisplaySettings { get; set; }
        public virtual ICollection<ZoneMain1> ZoneMain1 { get; set; }
        public virtual ZonesSettings ZonesSettings { get; set; }
    }
}
