//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device_DisplaySettings
    {
        public long ConfigID { get; set; }
        public Nullable<int> DisplayCharset { get; set; }
        public byte TempratureUnit { get; set; }
        public byte ClockViewTypeID { get; set; }
    
        public virtual listClockView listClockView { get; set; }
        public virtual listTempratureUnit listTempratureUnit { get; set; }
        public virtual ConfigManager ConfigManager { get; set; }
    }
}
