//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceMain
    {
        public DeviceMain()
        {
            this.AlertSetting = new HashSet<AlertSetting>();
            this.KeyValue = new HashSet<KeyValue>();
        }
    
        public long DeviceID { get; set; }
        public string SN { get; set; }
        public Nullable<long> ParentSiteID { get; set; }
        public string Name { get; set; }
        public bool IsAlertsEnabled { get; set; }
        public int DeviceModelID { get; set; }
        public int TotalActivatedZones { get; set; }
        public int StatusID { get; set; }
        public string Map_Latitude { get; set; }
        public string Map_Longitude { get; set; }
        public string FirmwareVersion { get; set; }
        public Nullable<byte> WaterSavingAlgorithmID { get; set; }
        public Nullable<long> ConfigID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> LastSynchronizeDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> HoldUntilDate { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
    
        public virtual GlobalizationZone GlobalizationZone { get; set; }
        public virtual ICollection<AlertSetting> AlertSetting { get; set; }
        public virtual ConfigManager ConfigManager { get; set; }
        public virtual listModel listModel { get; set; }
        public virtual listStatus listStatus { get; set; }
        public virtual Site Site { get; set; }
        public virtual ICollection<KeyValue> KeyValue { get; set; }
    }
}
