//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalizationZone
    {
        public GlobalizationZone()
        {
            this.DeviceMain = new HashSet<DeviceMain>();
            this.Site = new HashSet<Site>();
        }
    
        public int ZoneID { get; set; }
        public string SystemZoneID { get; set; }
        public string DisplayName { get; set; }
        public string DaylightName { get; set; }
        public string StandardName { get; set; }
        public int GMTOffset { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<int> ManualOffset { get; set; }
        public Nullable<bool> IsDaylightTime { get; set; }
        public Nullable<int> ActualOffset { get; set; }
    
        public virtual ICollection<DeviceMain> DeviceMain { get; set; }
        public virtual ICollection<Site> Site { get; set; }
    }
}
