//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyValue
    {
        public long KeyID { get; set; }
        public long DeviceID { get; set; }
        public string Code { get; set; }
        public string Value { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual DeviceMain DeviceMain { get; set; }
    }
}
