//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class linkEra2Session
    {
        public long EraID { get; set; }
        public long SessionID { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual EraSetting EraSetting { get; set; }
        public virtual SessionSetting SessionSetting { get; set; }
    }
}
