//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class listWaterSavingAlgorithm
    {
        public listWaterSavingAlgorithm()
        {
            this.Site = new HashSet<Site>();
        }
    
        public byte AlgorithmID { get; set; }
        public byte[] Name { get; set; }
    
        public virtual ICollection<Site> Site { get; set; }
    }
}
