//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class listSessionRestrictionType
    {
        public listSessionRestrictionType()
        {
            this.SessionSetting = new HashSet<SessionSetting>();
        }
    
        public byte RestrictionTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SessionSetting> SessionSetting { get; set; }
    }
}
