//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class listTempratureUnit
    {
        public listTempratureUnit()
        {
            this.Device_DisplaySettings = new HashSet<Device_DisplaySettings>();
        }
    
        public byte UnitID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Device_DisplaySettings> Device_DisplaySettings { get; set; }
    }
}
