//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.UserAccount = new HashSet<UserAccount>();
            this.SharedSite = new HashSet<SharedSite>();
        }
    
        public string Name { get; set; }
        public long ProjectID { get; set; }
    
        public virtual ICollection<UserAccount> UserAccount { get; set; }
        public virtual ICollection<SharedSite> SharedSite { get; set; }
        public virtual Site Site { get; set; }
    }
}
