//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionSetting
    {
        public SessionSetting()
        {
            this.linkEra2Session = new HashSet<linkEra2Session>();
            this.SessionDaySetting = new HashSet<SessionDaySetting>();
        }
    
        public long SessionID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsIrrigationAllowed { get; set; }
        public bool IsAutoUpdate { get; set; }
        public int SessionIndex { get; set; }
        public byte RestrictionType { get; set; }
    
        public virtual ICollection<linkEra2Session> linkEra2Session { get; set; }
        public virtual listSessionRestrictionType listSessionRestrictionType { get; set; }
        public virtual ICollection<SessionDaySetting> SessionDaySetting { get; set; }
    }
}
