//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionDaySetting
    {
        public long ParentSessionID { get; set; }
        public byte DayIndex { get; set; }
        public bool IsIrrigationAllowed { get; set; }
        public int StartTimeSeconds { get; set; }
        public int EndTimeSeconds { get; set; }
        public int MaxDailyIrrigrationSeconds { get; set; }
        public int MaxDailyCycles { get; set; }
    
        public virtual SessionSetting SessionSetting { get; set; }
    }
}
