//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public long UserID { get; set; }
        public long ProjectID { get; set; }
        public System.DateTime MatchDate { get; set; }
    
        public virtual LoginUser LoginUser { get; set; }
        public virtual Project Project { get; set; }
    }
}
