//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterSavingAlgorithm_P1
    {
        public long SiteID { get; set; }
        public bool IsEnabled { get; set; }
        public decimal HottestMonthTemp { get; set; }
        public decimal NormalHumidity { get; set; }
        public decimal PreciptationTreshold { get; set; }
        public decimal ChangeTemp_Per5Deg { get; set; }
        public decimal ChangeHumidity_Per5Precent { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
