//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonesSettings
    {
        public long ConfigID { get; set; }
        public int OpenTiming { get; set; }
        public int CloseTiming { get; set; }
        public byte OpenSequenceTypeID { get; set; }
        public byte CloseSequenceTypeID { get; set; }
        public Nullable<byte> CycleSoakPattern { get; set; }
    
        public virtual listCycleSoakPattern listCycleSoakPattern { get; set; }
        public virtual listOperationSequence listOperationSequence { get; set; }
        public virtual listOperationSequence listOperationSequence1 { get; set; }
        public virtual ConfigManager ConfigManager { get; set; }
    }
}
