//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneMain1
    {
        public long ConfigID { get; set; }
        public long ZoneID { get; set; }
    
        public virtual ZoneMain ZoneMain { get; set; }
        public virtual ConfigManager ConfigManager { get; set; }
    }
}
