CREATE   PROCEDURE  [etl].[MergeUsersToOnPrem]
AS
MERGE INTO [dbo].[Users] AS dest
USING (
	SELECT [ID]
		,[FirstName]
		,[LastName]
		,[FirstNameEng]
		,[LastNameEng]
		,[Email]
		,[Password]
		,[Phone]
		,[IsActive]
		,[CreatedDate]
		,[UpdatedDate]
		,0 as [UpdateUserID]
		,[UserAddress]
		,[LocationArea]
		,[Stamp]
	FROM [etl].[Users]
	) AS source
	ON dest.AWSID = source.ID
WHEN MATCHED
	THEN
		UPDATE
		SET  dest.[FirstName] = source.[FirstName]
			,dest.[LastName] = source.[LastName]
			,dest.[FirstNameEng] = source.[FirstNameEng]
			,dest.[LastNameEng] = source.[LastNameEng]
			,dest.[Email] = source.[Email]
			,dest.[Password] = source.[Password]
			,dest.[Phone] = source.[Phone]
			,dest.[IsActive] = source.[IsActive]
			,dest.[CreatedDate] = source.[CreatedDate]
			,dest.[UpdatedDate] = source.[UpdatedDate]
			,dest.[UpdateUserID] = source.[UpdateUserID]
			,dest.[UserAddress] = source.[UserAddress]
			,dest.[LocationArea] = source.[LocationArea]
			,dest.[Stamp] = source.[Stamp]
WHEN NOT MATCHED BY TARGET
	THEN
		INSERT (
             [FirstName]
			,[LastName]
			,[FirstNameEng]
			,[LastNameEng]
			,[Email]
			,[Password]
			,[Phone]
			,[IsActive]
			,[CreatedDate]
			,[UpdatedDate]
			,[UpdateUserID]
			,[UserAddress]
			,[LocationArea]
			,[Stamp]
			,[AWSID]
			)
		VALUES (
             source.[FirstName]
			,source.[LastName]
			,source.[FirstNameEng]
			,source.[LastNameEng]
			,source.[Email]
			,source.[Password]
			,source.[Phone]
			,source.[IsActive]
			,source.[CreatedDate]
			,source.[UpdatedDate]
			,source.[UpdateUserID]
			,source.[UserAddress]
			,source.[LocationArea]
			,source.[Stamp]
			,source.[ID]
			);