CREATE TABLE [dbo].[CustomerDevices] (
    [CustomerId]                  INT            NOT NULL,
    [CustomerDeviceID]            INT            IDENTITY (1, 1) NOT NULL,
    [MainCategoryId]              INT            NULL,
    [SecondaryCategoryId]         INT            NULL,
    [CustomerSiteId]              INT            NULL,
    [CustomerContactId]           INT            NULL,
    [OrdersProductTypeId]         INT            NULL,
    [Accuracy]                    TINYINT        NULL,
    [OrdersDeviceManufacturer]    NVARCHAR (100) NULL,
    [DeviceLocation]              NVARCHAR (50)  NULL,
    [LastAdjustmentDate]          DATETIME2 (0)  NULL,
    [Model]                       NVARCHAR (150) NULL,
    [SerialNumber]                NVARCHAR (50)  NULL,
    [ManufacturerNumber]          NVARCHAR (100) NULL,
    [AdditionalDeviceNumber]      NVARCHAR (100) NULL,
    [DateFormatStructure]         NVARCHAR (20)  NULL,
    [NextCalibrationDate]         DATETIME2 (0)  NULL,
    [CalibrationIntervalMonths]   TINYINT        NULL,
    [ReportLanguage]              NVARCHAR (50)  NULL,
    [IsThirdPartyCalibration]     BIT            DEFAULT ((0)) NULL,
    [BatteriesReplacement]        BIT            DEFAULT ((0)) NULL,
    [CalibrationMethod]           NVARCHAR (100) NULL,
    [SpecificationReferenceId]    INT            NULL,
    [MeasurementsSpecificationId] INT            NULL,
    [PrimaryMeasurmentUnitId]     INT            NULL,
    [SecondaryMeasurmentUnitId]   INT            NULL,
    [CreatedDate]                 DATETIME2 (0)  DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                 DATETIME2 (0)  NULL,
    [UpdateUserID]                INT            NULL,
    [IsDeleted]                   BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CustomerDevices] PRIMARY KEY CLUSTERED ([CustomerId] ASC, [CustomerDeviceID] ASC),
    CONSTRAINT [FK_CustomerDevices_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customers] ([CustomerId]),
    CONSTRAINT [FK_CustomerDevices_MainCategoryId] FOREIGN KEY ([MainCategoryId]) REFERENCES [dbo].[MainCategories] ([ID]),
    CONSTRAINT [FK_CustomerDevices_MeasurementsSpecificationId] FOREIGN KEY ([MeasurementsSpecificationId]) REFERENCES [dbo].[MeasurementsSpecifications] ([ID]),
    CONSTRAINT [FK_CustomerDevices_OrdersProductTypeId] FOREIGN KEY ([OrdersProductTypeId]) REFERENCES [dbo].[OrdersProductTypes] ([OrdersProductTypeId]),
    CONSTRAINT [FK_CustomerDevices_PrimaryMeasurmentUnitId] FOREIGN KEY ([PrimaryMeasurmentUnitId]) REFERENCES [dbo].[MeasurementDeviceUnits] ([MeasurementDeviceUnitId]),
    CONSTRAINT [FK_CustomerDevices_SecondaryCategoryId] FOREIGN KEY ([SecondaryCategoryId]) REFERENCES [dbo].[SecondaryCategories] ([ID]),
    CONSTRAINT [FK_CustomerDevices_SecondaryMeasurmentUnitId] FOREIGN KEY ([SecondaryMeasurmentUnitId]) REFERENCES [dbo].[MeasurementDeviceUnits] ([MeasurementDeviceUnitId]),
    CONSTRAINT [FK_CustomerDevices_SpecificationReferenceId] FOREIGN KEY ([SpecificationReferenceId]) REFERENCES [dbo].[SpecificationReference] ([ID])
);

