CREATE TABLE [dbo].[MeasurementDevices] (
    [ID]               INT             IDENTITY (1, 1) NOT NULL,
    [MabaID]           VARCHAR (50)    NOT NULL,
    [CreateDate]       DATETIME2 (7)   CONSTRAINT [DF_MeasurementDevices_Added] DEFAULT (getdate()) NULL,
    [RemoveDate]       DATETIME2 (7)   NULL,
    [Description]      NVARCHAR (50)   NULL,
    [ManufacturerId]   INT             NULL,
    [Model]            NVARCHAR (150)  NULL,
    [SerialNumber]     NVARCHAR (50)   NULL,
    [NextCalibration]  DATETIME        NULL,
    [Note]             NVARCHAR (150)  NULL,
    [CalibrationDate]  DATETIME2 (7)   NULL,
    [MeasurementId]    INT             NULL,
    [MainClass]        INT             NOT NULL,
    [SubClass]         INT             NULL,
    [ExtraCalTools]    NVARCHAR (150)  NULL,
    [DepartmentId]     INT             NULL,
    [Unit]             INT             NULL,
    [CalibratorId]     INT             NULL,
    [ReportNumber]     NVARCHAR (50)   NULL,
    [WorkRangeUnit]    INT             NULL,
    [WorkRangeMin]     NUMERIC (18, 6) NULL,
    [WorkRangeMax]     NUMERIC (18, 6) NULL,
    [DefaultPrecision] INT             CONSTRAINT [DF_MeasurementDevices_DefaultPrecision] DEFAULT (NULL) NULL,
    [HighestPrecision] INT             CONSTRAINT [DF_MeasurementDevices_HighestPrecision] DEFAULT (NULL) NULL,
    [UpdateDate]       DATETIME2 (7)   NULL,
    [UpdateUserID]     INT             NULL,
    [AllowMinOOR]      BIT             CONSTRAINT [DF_MeasurementDevices_AllowMinOOR] DEFAULT ((0)) NOT NULL,
    [AllowMaxOOR]      BIT             CONSTRAINT [DF_MeasurementDevices_AllowMaxOOR] DEFAULT ((0)) NOT NULL,
    [IsDeleted]        BIT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_MeasurementDevices] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_MeasurementDevices_MeasurementDevicesMainClasses] FOREIGN KEY ([MainClass]) REFERENCES [dbo].[MeasurementDevicesMainClasses] ([Id]),
    CONSTRAINT [FK_MeasurementDevices_MeasurementDevicesManufacturers] FOREIGN KEY ([ManufacturerId]) REFERENCES [dbo].[MeasurementDevicesManufacturers] ([ID]),
    CONSTRAINT [FK_MeasurementDevices_MeasurementDevicesSubClass] FOREIGN KEY ([SubClass]) REFERENCES [dbo].[MeasurementDevicesSubClass] ([ID]),
    CONSTRAINT [FK_MeasurementDevices_Measurements] FOREIGN KEY ([MeasurementId]) REFERENCES [dbo].[Measurements] ([ID]),
    CONSTRAINT [FK_MeasurementDevices_Units] FOREIGN KEY ([Unit]) REFERENCES [dbo].[Units] ([ID]),
    CONSTRAINT [FK_MeasurementDevices_Units1] FOREIGN KEY ([WorkRangeUnit]) REFERENCES [dbo].[Units] ([ID])
);

