CREATE TABLE [dbo].[MeasurementDevices] (
    [ID]                        INT             IDENTITY (1, 1) NOT NULL,
    [MabaID]                    NVARCHAR (50)   NOT NULL,
    [Description]               NVARCHAR (50)   NULL,
    [ManufacturerId]            INT             NULL,
    [Model]                     NVARCHAR (150)  NULL,
    [SerialNumber]              NVARCHAR (50)   NULL,
    [NextCalibration]           DATETIME2 (0)   NULL,
    [Note]                      NVARCHAR (150)  NULL,
    [CalibrationDate]           DATETIME2 (7)   NULL,
    [MeasurementId]             INT             NULL,
    [MainClassId]               INT             NULL,
    [SubClassId]                INT             NULL,
    [ExtraCalTools]             NVARCHAR (150)  NULL,
    [MainCategoryId]            INT             NULL,
    [UnitId]                    INT             NULL,
    [CalibratorId]              INT             NULL,
    [ReportNumber]              NVARCHAR (50)   NULL,
    [WorkRangeUnitId]           INT             NULL,
    [WorkRangeMin]              NUMERIC (18, 6) NULL,
    [WorkRangeMax]              NUMERIC (18, 6) NULL,
    [DefaultPrecision]          INT             NULL,
    [HighestPrecision]          INT             NULL,
    [CreateDate]                DATETIME2 (7)   DEFAULT (getdate()) NULL,
    [RemoveDate]                DATETIME2 (7)   NULL,
    [UpdateDate]                DATETIME2 (7)   NULL,
    [UpdateUserID]              INT             NULL,
    [AllowMinOOR]               BIT             CONSTRAINT [DF_MeasurementDevices_AllowMinOOR] DEFAULT ((0)) NULL,
    [AllowMaxOOR]               BIT             CONSTRAINT [DF_MeasurementDevices_AllowMaxOOR] DEFAULT ((0)) NULL,
    [IsDeleted]                 BIT             DEFAULT ((0)) NOT NULL,
    [Resolution]                INT             NULL,
    [MeasurementDeviceSourceId] INT             NULL,
    [MeasurementDeviceStatusId] INT             NULL,
    [IP]                        NVARCHAR (50)   NULL,
    [Connection]                NVARCHAR (50)   NULL,
    [SecondaryCategoryId]       INT             NULL,
    CONSTRAINT [PK_MeasurementDevices] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_MeasurementDevices_CalibratorId] FOREIGN KEY ([CalibratorId]) REFERENCES [dbo].[Users] ([ID]),
    CONSTRAINT [FK_MeasurementDevices_MainCategoryId] FOREIGN KEY ([MainCategoryId]) REFERENCES [dbo].[MainCategories] ([ID]),
    CONSTRAINT [FK_MeasurementDevices_MainClassId] FOREIGN KEY ([MainClassId]) REFERENCES [dbo].[MeasurementDevicesMainClasses] ([Id]),
    CONSTRAINT [FK_MeasurementDevices_ManufacturerId] FOREIGN KEY ([ManufacturerId]) REFERENCES [dbo].[MeasurementDevicesManufacturers] ([ID]),
    CONSTRAINT [FK_MeasurementDevices_MeasurementDevicesMainClasses] FOREIGN KEY ([MainClassId]) REFERENCES [dbo].[MeasurementDevicesMainClasses] ([Id]),
    CONSTRAINT [FK_MeasurementDevices_Measurements] FOREIGN KEY ([MeasurementId]) REFERENCES [dbo].[Measurements] ([ID]),
    CONSTRAINT [FK_MeasurementDevices_SecondaryCategoryId] FOREIGN KEY ([SecondaryCategoryId]) REFERENCES [dbo].[SecondaryCategories] ([ID]),
    CONSTRAINT [FK_MeasurementDevices_StatusId] FOREIGN KEY ([MeasurementDeviceStatusId]) REFERENCES [dbo].[Statuses] ([StatusId]),
    CONSTRAINT [FK_MeasurementDevices_SubClassId] FOREIGN KEY ([SubClassId]) REFERENCES [dbo].[MeasurementDevicesSubClass] ([ID]),
    CONSTRAINT [FK_MeasurementDevices_UnitId] FOREIGN KEY ([UnitId]) REFERENCES [dbo].[MeasurementDeviceUnits] ([MeasurementDeviceUnitId]),
    CONSTRAINT [FK_MeasurementDevices_UpdateUserID] FOREIGN KEY ([UpdateUserID]) REFERENCES [dbo].[Users] ([ID]),
    CONSTRAINT [FK_MeasurementDevices_WorkRangeUnitId] FOREIGN KEY ([WorkRangeUnitId]) REFERENCES [dbo].[MeasurementDeviceUnits] ([MeasurementDeviceUnitId])
);

