CREATE TABLE [dbo].[MeasurementDevicesCorrections] (
    [ID]                                    INT              IDENTITY (1, 1) NOT NULL,
    [Value1]                                DECIMAL (25, 15) NOT NULL,
    [Value2]                                DECIMAL (25, 15) NULL,
    [Deviation]                             DECIMAL (35, 15) NULL,
    [Note]                                  NVARCHAR (300)   NULL,
    [MeasurementDevicesId]                  INT              NULL,
    [MeasurementId]                         INT              NULL,
    [UnitID]                                INT              NULL,
    [CorVersion]                            INT              CONSTRAINT [DF_MeasurementDevicesCorrections_CorVersion] DEFAULT ((1)) NULL,
    [MainCategoryId]                        INT              NULL,
    [Equation]                              NVARCHAR (300)   NULL,
    [CreatedDate]                           DATETIME2 (0)    DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                           DATETIME2 (0)    NULL,
    [IsDeleted]                             BIT              DEFAULT ((0)) NOT NULL,
    [UpdateUserID]                          INT              NULL,
    [MeasurementDevicesCorrectionsSourceId] INT              NULL,
    CONSTRAINT [PK_tblInstrCorrections] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_MeasurementDevicesCorrections_MainCategoryId] FOREIGN KEY ([MainCategoryId]) REFERENCES [dbo].[MainCategories] ([ID]),
    CONSTRAINT [FK_MeasurementDevicesCorrections_MeasurementDevicesId] FOREIGN KEY ([MeasurementDevicesId]) REFERENCES [dbo].[MeasurementDevices] ([ID]),
    CONSTRAINT [FK_MeasurementDevicesCorrections_MeasurementId] FOREIGN KEY ([MeasurementId]) REFERENCES [dbo].[Measurements] ([ID]),
    CONSTRAINT [FK_MeasurementDevicesCorrections_UnitID] FOREIGN KEY ([UnitID]) REFERENCES [dbo].[MeasurementDeviceUnits] ([MeasurementDeviceUnitId]),
    CONSTRAINT [FK_MeasurementDevicesCorrections_UpdateUserID] FOREIGN KEY ([UpdateUserID]) REFERENCES [dbo].[Users] ([ID])
);

