CREATE TABLE [dbo].[OrderDetailsItems] (
    [OrderDetailId]              INT             NOT NULL,
    [OrderDetailsItemId]         INT             IDENTITY (1, 1) NOT NULL,
    [NextCalibrationDate]        DATETIME2 (0)   NULL,
    [SerialNumber]               NVARCHAR (100)  NULL,
    [ManufacturerNumber]         NVARCHAR (100)  NULL,
    [DeviceModel]                NVARCHAR (100)  NULL,
    [AdditionalDeviceNumber]     NVARCHAR (100)  NULL,
    [MbaReportNumber]            NVARCHAR (100)  NULL,
    [MainCategoryId]             INT             NULL,
    [SecondaryCategoryId]        INT             NULL,
    [OrdersDeviceManufacturerId] INT             NULL,
    [SERN]                       INT             NULL,
    [CalibrationSpecificationId] INT             NULL,
    [SpecificationReferenceId]   INT             NULL,
    [MeasurementUnitId]          INT             NULL,
    [MeasurementPoints]          INT             NULL,
    [MeasurementValueList]       NVARCHAR (MAX)  NULL,
    [ProductLocation]            NVARCHAR (50)   NULL,
    [CreatedDate]                DATETIME2 (0)   DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                DATETIME2 (0)   NULL,
    [CreatedByUserId]            INT             NULL,
    [UpdateUserID]               INT             NULL,
    [IsDeleted]                  BIT             DEFAULT ((0)) NOT NULL,
    [IsCancelled]                BIT             DEFAULT ((0)) NOT NULL,
    [CalibrationStatusId]        INT             NULL,
    [CalibrationReportStatusId]  INT             NULL,
    [ActualCalibrationDate]      DATETIME2 (0)   NULL,
    [CalibrationStoppedComment]  NVARCHAR (1000) NULL,
    CONSTRAINT [PK_OrderDetailsItems] PRIMARY KEY CLUSTERED ([OrderDetailId] ASC, [OrderDetailsItemId] ASC),
    CONSTRAINT [FK_OrderDetailsItems_CalibrationReportStatusId] FOREIGN KEY ([CalibrationReportStatusId]) REFERENCES [dbo].[Statuses] ([StatusId]),
    CONSTRAINT [FK_OrderDetailsItems_CalibrationSpecificationId] FOREIGN KEY ([CalibrationSpecificationId]) REFERENCES [dbo].[MeasurementsSpecifications] ([ID]),
    CONSTRAINT [FK_OrderDetailsItems_CalibrationStatusId] FOREIGN KEY ([CalibrationStatusId]) REFERENCES [dbo].[Statuses] ([StatusId]),
    CONSTRAINT [FK_OrderDetailsItems_CreatedByUserId] FOREIGN KEY ([CreatedByUserId]) REFERENCES [dbo].[Users] ([ID]),
    CONSTRAINT [FK_OrderDetailsItems_MeasurementUnitId] FOREIGN KEY ([MeasurementUnitId]) REFERENCES [dbo].[MeasurementDeviceUnits] ([MeasurementDeviceUnitId]),
    CONSTRAINT [FK_OrderDetailsItems_OrdersDeviceManufacturerId] FOREIGN KEY ([OrdersDeviceManufacturerId]) REFERENCES [dbo].[OrdersDeviceManufacturers] ([OrdersDeviceManufacturerId]),
    CONSTRAINT [FK_OrderDetailsItems_OrdersMainCategoryId] FOREIGN KEY ([MainCategoryId]) REFERENCES [dbo].[MainCategories] ([ID]),
    CONSTRAINT [FK_OrderDetailsItems_OrdersSecondaryCategoryId] FOREIGN KEY ([SecondaryCategoryId]) REFERENCES [dbo].[SecondaryCategories] ([ID]),
    CONSTRAINT [FK_OrderDetailsItems_SpecificationReferenceId] FOREIGN KEY ([SpecificationReferenceId]) REFERENCES [dbo].[SpecificationReference] ([ID]),
    CONSTRAINT [FK_OrderDetailsItems_UpdatedByUserId] FOREIGN KEY ([UpdateUserID]) REFERENCES [dbo].[Users] ([ID])
);

