CREATE TABLE [dbo].[OrderDetailsItems] (
    [OrderDetailId]              INT            NOT NULL,
    [OrderDetailsItemId]         INT            IDENTITY (1, 1) NOT NULL,
    [ActualCalibrationDate]      DATETIME2 (0)  NULL,
    [NextCalibrationDate]        DATETIME2 (0)  NULL,
    [SerialNumber]               NVARCHAR (100) NULL,
    [ManufacturerNumber]         NVARCHAR (100) NULL,
    [DeviceModel]                NVARCHAR (100) NULL,
    [AdditionalDeviceNumber]     NVARCHAR (100) NULL,
    [MbaReportNumber]            NVARCHAR (100) NULL,
    [OrdersMainCategoryId]       INT            NULL,
    [OrdersSecondaryCategoryId]  INT            NULL,
    [OrdersDeviceManufacturerId] INT            NULL,
    [SERN]                       INT            NULL,
    [CalibrationSpecificationId] INT            NULL,
    [SpecificationReferenceId]   INT            NULL,
    [MeasurementUnitId]          INT            NULL,
    [MeasurementPoints]          INT            NULL,
    [MeasurementValueList]       NVARCHAR (200) NULL,
    [ProductLocation]            NVARCHAR (50)  NULL,
    [CreatedDate]                DATETIME2 (0)  DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                DATETIME2 (0)  NULL,
    [CreatedByUserId]            INT            NULL,
    [UpdateUserID]               INT            NULL,
    [IsDeleted]                  BIT            DEFAULT ((0)) NOT NULL,
    [IsCancelled]                BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_OrderDetailsItems] PRIMARY KEY CLUSTERED ([OrderDetailId] ASC, [OrderDetailsItemId] ASC),
    CONSTRAINT [FK_OrderDetailsItems_CalibrationSpecificationId] FOREIGN KEY ([CalibrationSpecificationId]) REFERENCES [dbo].[MeasurementsSpecifications] ([ID]),
    CONSTRAINT [FK_OrderDetailsItems_CreatedByUserId] FOREIGN KEY ([CreatedByUserId]) REFERENCES [dbo].[Users] ([ID]),
    CONSTRAINT [FK_OrderDetailsItems_MeasurementUnitId] FOREIGN KEY ([MeasurementUnitId]) REFERENCES [dbo].[MeasurementDeviceUnits] ([MeasurementDeviceUnitId]),
    CONSTRAINT [FK_OrderDetailsItems_OrdersDeviceManufacturerId] FOREIGN KEY ([OrdersDeviceManufacturerId]) REFERENCES [dbo].[OrdersDeviceManufacturers] ([OrdersDeviceManufacturerId]),
    CONSTRAINT [FK_OrderDetailsItems_OrdersMainCategoryId] FOREIGN KEY ([OrdersMainCategoryId]) REFERENCES [dbo].[OrdersMainCategories] ([OrdersMainCategoryId]),
    CONSTRAINT [FK_OrderDetailsItems_OrdersSecondaryCategoryId] FOREIGN KEY ([OrdersSecondaryCategoryId]) REFERENCES [dbo].[OrdersSecondaryCategories] ([OrdersSecondaryCategoryId]),
    CONSTRAINT [FK_OrderDetailsItems_SpecificationReferenceId] FOREIGN KEY ([SpecificationReferenceId]) REFERENCES [dbo].[SpecificationReference] ([ID]),
    CONSTRAINT [FK_OrderDetailsItems_UpdatedByUserId] FOREIGN KEY ([UpdateUserID]) REFERENCES [dbo].[Users] ([ID])
);

