CREATE TABLE [dbo].[OrderDetails] (
    [OrderDetailId]        INT            IDENTITY (1, 1) NOT NULL,
    [OrderWorkPlanId]      INT            NOT NULL,
    [CustomerName]         NVARCHAR (255) NULL,
    [CustomerCity]         NVARCHAR (50)  NULL,
    [CustomerID]           NVARCHAR (16)  NOT NULL,
    [CustomerPhone]        NVARCHAR (20)  NOT NULL,
    [CustomerContactName]  NVARCHAR (37)  NULL,
    [CustomerAddress]      NVARCHAR (100) NULL,
    [CustomerContactPhone] NVARCHAR (20)  NULL,
    [MBAContactName]       NVARCHAR (32)  NOT NULL,
    [MBAContactPhone]      NVARCHAR (20)  NOT NULL,
    [MBAContactMobile]     NVARCHAR (20)  NOT NULL,
    [MainCategoties]       NVARCHAR (500) NULL,
    [IsInHouse]            BIT            NOT NULL,
    [Notes]                NVARCHAR (255) NULL,
    [PartName]             NVARCHAR (60)  NULL,
    [DeviceDescription]    NVARCHAR (50)  NULL,
    [DepartmentId]         INT            NULL,
    [MbaReportNumber]      NVARCHAR (20)  NOT NULL,
    [CalibDate]            DATETIME2 (0)  NULL,
    [NextCalibDate]        DATETIME2 (0)  NULL,
    [CALIBMONTH]           INT            NULL,
    [ReturnDate]           DATETIME       NULL,
    [PartDescription]      NVARCHAR (59)  NULL,
    [IsCancelled]          BIT            DEFAULT ((0)) NOT NULL,
    [StatusId]             INT            NULL,
    [CalibStatud]          NVARCHAR (12)  NULL,
    [PART]                 INT            NULL,
    [SerialNumber]         NVARCHAR (20)  NULL,
    [DeviceManufacturer]   NVARCHAR (255) NULL,
    [DeviceModel]          NVARCHAR (30)  NULL,
    [Klita]                NVARCHAR (20)  NOT NULL,
    [CreatedDate]          DATETIME2 (0)  DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]          DATETIME2 (0)  NULL,
    [CreatedByUserId]      INT            NULL,
    [UpdatedByUserId]      INT            NULL,
    [ClientRemarkId]       INT            NULL,
    CONSTRAINT [PK_OrderDetails] PRIMARY KEY CLUSTERED ([OrderDetailId] ASC, [OrderWorkPlanId] ASC),
    CONSTRAINT [FK_OrderDetails_ClientRemarkId] FOREIGN KEY ([ClientRemarkId]) REFERENCES [dbo].[ClientRemarks] ([ClientRemarkId]),
    CONSTRAINT [FK_OrderDetails_CreatedByUserId] FOREIGN KEY ([CreatedByUserId]) REFERENCES [dbo].[Users] ([ID]),
    CONSTRAINT [FK_OrderDetails_OrderWorkPlanId] FOREIGN KEY ([OrderWorkPlanId]) REFERENCES [dbo].[OrderWorkPlans] ([OrderWorkPlanId]),
    CONSTRAINT [FK_OrderDetails_StatusId] FOREIGN KEY ([StatusId]) REFERENCES [dbo].[Statuses] ([StatusId]),
    CONSTRAINT [FK_OrderDetails_UpdatedByUserId] FOREIGN KEY ([UpdatedByUserId]) REFERENCES [dbo].[Users] ([ID])
);

