CREATE TABLE [dbo].[OrderDetails] (
    [OrderWorkPlanId]            INT             NOT NULL,
    [OrderDetailId]              INT             IDENTITY (1, 1) NOT NULL,
    [CalibDate]                  DATETIME2 (0)   NULL,
    [SerialNumber]               NVARCHAR (20)   NULL,
    [ManufacturerNumber]         NVARCHAR (17)   NULL,
    [DeviceModel]                NVARCHAR (30)   NULL,
    [SpecialCareTypeId]          INT             NULL,
    [IsInHouse]                  INT             NULL,
    [PartName]                   NVARCHAR (22)   NULL,
    [DeviceType]                 NVARCHAR (59)   NULL,
    [MbaReportNumber]            INT             NULL,
    [OrdersMainCategoryId]       INT             NULL,
    [OrdersSecondaryCategoryId]  INT             NULL,
    [OrdersDeviceManufacturerId] INT             NULL,
    [SecondCategory]             NVARCHAR (48)   NULL,
    [CustomerId]                 INT             NULL,
    [StatusId]                   INT             NULL,
    [KLINE]                      INT             NULL,
    [SERN]                       INT             NULL,
    [CreatedDate]                DATETIME2 (0)   DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                DATETIME2 (0)   NULL,
    [CreatedByUserId]            INT             NULL,
    [UpdateUserID]               INT             NULL,
    [IsDeleted]                  BIT             DEFAULT ((0)) NOT NULL,
    [IsCancelled]                BIT             DEFAULT ((0)) NOT NULL,
    [VPRICE]                     DECIMAL (18, 2) NULL,
    [PRICE]                      DECIMAL (18, 2) NULL,
    [PART]                       INT             NULL,
    CONSTRAINT [PK_OrderDetails] PRIMARY KEY CLUSTERED ([OrderDetailId] ASC, [OrderWorkPlanId] ASC),
    CONSTRAINT [FK_OrderDetails] FOREIGN KEY ([SpecialCareTypeId]) REFERENCES [dbo].[Statuses] ([StatusId]),
    CONSTRAINT [FK_OrderDetails_CreatedByUserId] FOREIGN KEY ([CreatedByUserId]) REFERENCES [dbo].[Users] ([ID]),
    CONSTRAINT [FK_OrderDetails_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customers] ([CustomerId]),
    CONSTRAINT [FK_OrderDetails_OrdersDeviceManufacturerId] FOREIGN KEY ([OrdersDeviceManufacturerId]) REFERENCES [dbo].[OrdersDeviceManufacturers] ([OrdersDeviceManufacturerId]),
    CONSTRAINT [FK_OrderDetails_OrdersMainCategoryId] FOREIGN KEY ([OrdersMainCategoryId]) REFERENCES [dbo].[OrdersMainCategories] ([OrdersMainCategoryId]),
    CONSTRAINT [FK_OrderDetails_StatusId] FOREIGN KEY ([StatusId]) REFERENCES [dbo].[Statuses] ([StatusId]),
    CONSTRAINT [FK_OrderDetails_UpdatedByUserId] FOREIGN KEY ([UpdateUserID]) REFERENCES [dbo].[Users] ([ID])
);

