CREATE TABLE [stg].[stg_Orders] (
    [OrderNumber]          NVARCHAR (16)  NOT NULL,
    [OpenDate]             DATETIME       NULL,
    [CustomerID]           NVARCHAR (16)  NOT NULL,
    [CustomerName]         NVARCHAR (100) NULL,
    [CustomerPhone]        NVARCHAR (20)  NOT NULL,
    [CustomerContactName]  NVARCHAR (37)  NULL,
    [CustomerCity]         NVARCHAR (100) NULL,
    [CustomerAddress]      NVARCHAR (100) NULL,
    [CustomerContactPhone] NVARCHAR (20)  NULL,
    [MBAContactName]       NVARCHAR (32)  NOT NULL,
    [MBAContactPhone]      NVARCHAR (20)  NOT NULL,
    [MBAContactMobile]     NVARCHAR (20)  NOT NULL,
    [ClientRemarks]        NVARCHAR (MAX) NULL,
    [MbaReportNumber]      NVARCHAR (20)  NULL,
    [SerialNumber]         NVARCHAR (20)  NULL,
    [ManufacturerNumber]   NVARCHAR (17)  NULL,
    [DeviceDescription]    NVARCHAR (48)  NULL,
    [Devicemodel]          NVARCHAR (30)  NULL,
    [CalibDate]            DATETIME       NULL,
    [NextCalibDate]        DATETIME       NULL,
    [CALIBMONTH]           INT            NULL,
    [ReturnDate]           DATETIME       NULL,
    [PartName]             NVARCHAR (22)  NULL,
    [PartDescription]      NVARCHAR (59)  NULL,
    [InHouse]              INT            NOT NULL,
    [DepartmentCode]       INT            NULL,
    [DepartmentName]       NVARCHAR (32)  NULL,
    [StatusCode]           INT            NULL,
    [CalibStatud]          NVARCHAR (12)  NULL,
    [DeviceManufacturer]   NVARCHAR (50)  NULL,
    [PART]                 INT            NULL,
    [Klita]                NVARCHAR (16)  NULL
);

