CREATE TABLE [stg].[stg_Orders] (
    [SourceOrderId]              INT             NULL,
    [ORDNAME]                    NVARCHAR (16)   NULL,
    [OpenDate]                   DATETIME        NULL,
    [CustomerSourceId]           INT             NULL,
    [SerialNumber]               NVARCHAR (50)   NULL,
    [ManufacturerNumber]         NVARCHAR (17)   NULL,
    [Devicemodel]                NVARCHAR (30)   NULL,
    [SpecialCareTypeId]          INT             NULL,
    [InHouse]                    INT             NULL,
    [MainCategorySourceId]       NVARCHAR (50)   NULL,
    [SecondCategorySourceId]     NVARCHAR (48)   NULL,
    [PartName]                   NVARCHAR (22)   NULL,
    [DeviceType]                 NVARCHAR (59)   NULL,
    [MbaReportNumber]            NVARCHAR (50)   NULL,
    [DeviceManufacturerSourceId] NVARCHAR (30)   NULL,
    [SourceSystem]               NVARCHAR (7)    NULL,
    [OrderLineCnt]               INT             NULL,
    [KLINE]                      INT             NULL,
    [SERN]                       INT             NULL,
    [CalibDate]                  DATETIME2 (0)   NULL,
    [VPRICE]                     DECIMAL (18, 2) NULL,
    [PRICE]                      DECIMAL (18, 2) NULL,
    [PART]                       INT             NULL,
    [ProductLocation]            NVARCHAR (50)   NULL,
    [ORDSTATUS]                  INT             NULL,
    [CustomerPackingExists]      BIT             NULL,
    [ActualReturnDate]           DATETIME2 (0)   NULL,
    [ExpectedReturnDate]         DATETIME2 (0)   NULL,
    [PackageLocation]            NVARCHAR (50)   NULL,
    [OrderDetailId]              INT             NULL,
    [ShipTypeDesc]               NVARCHAR (100)  NULL,
    [Doc]                        INT             NULL,
    [NextCalibrationDate]        DATETIME2 (0)   NULL,
    [AdditionalDeviceNumber]     NVARCHAR (100)  NULL,
    [CurrentCalibrationStatus]   NVARCHAR (10)   NULL,
    [CustomerReceivingDate]      DATETIME2 (0)   NULL,
    [ShippingDoc]                NVARCHAR (30)   NULL,
    [ShippingAddress]            NVARCHAR (150)  NULL,
    [DOC_N]                      INT             NULL,
    [DESTCODE]                   INT             NULL
);

