CREATE TABLE [stg].[stg_Orders] (
    [SourceOrderId]              INT             NULL,
    [ORDNAME]                    NVARCHAR (16)   NULL,
    [OpenDate]                   DATETIME        NULL,
    [CustomerSourceId]           INT             NULL,
    [SerialNumber]               NVARCHAR (20)   NULL,
    [ManufacturerNumber]         NVARCHAR (17)   NULL,
    [Devicemodel]                NVARCHAR (30)   NULL,
    [SpecialCareTypeId]          INT             NULL,
    [InHouse]                    INT             NULL,
    [MainCategorySourceId]       INT             NULL,
    [SecondCategorySourceId]     NVARCHAR (48)   NULL,
    [PartName]                   NVARCHAR (22)   NULL,
    [DeviceType]                 NVARCHAR (59)   NULL,
    [MbaReportNumber]            INT             NULL,
    [DeviceManufacturerSourceId] INT             NULL,
    [SourceSystem]               NVARCHAR (7)    NULL,
    [OrderLineCnt]               INT             NULL,
    [KLINE]                      INT             NULL,
    [SERN]                       INT             NULL,
    [CalibDate]                  DATETIME2 (0)   NULL,
    [VPRICE]                     DECIMAL (18, 2) NULL,
    [PRICE]                      DECIMAL (18, 2) NULL
);

