CREATE TABLE [stg].[stg_MeasurementDevices] (
    [MeasurementDeviceSourceId] INT             NULL,
    [MabaID]                    NVARCHAR (50)   NULL,
    [Description]               NVARCHAR (50)   NULL,
    [ManufacturerId]            INT             NULL,
    [Model]                     NVARCHAR (150)  NULL,
    [SerialNumber]              NVARCHAR (50)   NULL,
    [NextCalibration]           DATETIME2 (0)   NULL,
    [Note]                      NVARCHAR (150)  NULL,
    [CalibrationDate]           DATETIME2 (0)   NULL,
    [MeasurementId]             INT             NULL,
    [MainClassId]               INT             NULL,
    [SubClassId]                INT             NULL,
    [ExtraCalTools]             NVARCHAR (150)  NULL,
    [Department]                NVARCHAR (50)   NULL,
    [UnitId]                    INT             NULL,
    [CalibratorId]              INT             NULL,
    [ReportNumber]              NVARCHAR (50)   NULL,
    [WorkRangeUnitId]           INT             NULL,
    [WorkRangeMin]              NUMERIC (18, 6) NULL,
    [WorkRangeMax]              NUMERIC (18, 6) NULL,
    [DefaultPrecision]          INT             NULL,
    [HighestPrecision]          INT             NULL,
    [CreateDate]                DATETIME2 (0)   NULL,
    [RemoveDate]                DATETIME2 (0)   NULL,
    [AllowMinOOR]               BIT             NULL,
    [AllowMaxOOR]               BIT             NULL
);

