# Builds the .env that the installer ships to a calibration station.
#
# The installer used to bundle app\.env verbatim onto every customer machine. That file carries the
# staging database password, the SQL admin connection string, the SMTP password, a Chromatic token
# and seven test-account credentials - none of which a station uses. This keeps only what the app
# actually reads, so those secrets never leave the build machine.
#
# What survives, and why:
#   REMOTE_DATABASE_URL_PROD   the only required setting; start-webapp.ps1 derives
#                              REMOTE_DATABASE_URL from it at launch
#   NODE_ENV                   production
#   NEXT_PUBLIC_*              read by the app; the websocket URL is per-station
#   AWS_* / S3_BUCKET_NAME     src\server\aws\s3.ts backs the device-image router
#   CALIBRATION_LOGS_DIR       optional, read by api\local-serial-log
#   ALLOW_LOCAL_HARDWARE_LOG   optional station switch
#
# Console output is ASCII: Windows Server consoles render Hebrew as mojibake.

param(
    [string]$SourceEnv,
    [string]$OutFile
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
if (-not $SourceEnv) { $SourceEnv = Join-Path $root 'app\.env' }
if (-not $OutFile)   { $OutFile   = Join-Path $root 'Installer\assets\.env.station' }

if (-not (Test-Path $SourceEnv)) { throw "Source env not found: $SourceEnv" }

$keep = @(
    'REMOTE_DATABASE_URL_PROD',
    'NODE_ENV',
    'NEXT_PUBLIC_WEBSOCKET_URL',
    'NEXT_PUBLIC_CALIBRATION_USE_MOCK',
    'NEXT_PUBLIC_S3_BUCKET_DOMAIN',
    'AWS_ACCESS_KEY_ID',
    'AWS_SECRET_ACCESS_KEY',
    'AWS_REGION',
    'S3_BUCKET_NAME',
    'CALIBRATION_LOGS_DIR',
    'ALLOW_LOCAL_HARDWARE_LOG'
)

$seen = @{}
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Generated by scripts\New-StationEnv.ps1 - do not edit by hand.')
$lines.Add('# Only the settings a calibration station actually reads. REMOTE_DATABASE_URL itself is')
$lines.Add('# derived at launch by assets\start-webapp.ps1 from REMOTE_DATABASE_URL_PROD.')
$lines.Add('')

foreach ($line in (Get-Content -Path $SourceEnv -Encoding utf8)) {
    $m = [regex]::Match($line, '^\s*([A-Z_][A-Z0-9_]*)\s*=')
    if (-not $m.Success) { continue }
    $name = $m.Groups[1].Value
    if ($keep -notcontains $name) { continue }
    if ($seen.ContainsKey($name)) { continue }   # app\.env has a duplicate NEXT_PUBLIC_WEBSOCKET_URL
    $seen[$name] = $true
    $lines.Add($line.TrimEnd())
}

if (-not $seen.ContainsKey('NODE_ENV')) { $lines.Add('NODE_ENV=production') }

$dir = Split-Path -Parent $OutFile
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
Set-Content -Path $OutFile -Value $lines -Encoding utf8

$dropped = 0
foreach ($line in (Get-Content -Path $SourceEnv -Encoding utf8)) {
    $m = [regex]::Match($line, '^\s*([A-Z_][A-Z0-9_]*)\s*=')
    if ($m.Success -and ($keep -notcontains $m.Groups[1].Value)) { $dropped++ }
}
Write-Host ("Station env written: {0}" -f $OutFile)
Write-Host ("  kept {0} settings, dropped {1}" -f $seen.Count, $dropped)
