//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class listCycleSoakPattern
    {
        public listCycleSoakPattern()
        {
            this.ZonesSettings = new HashSet<ZonesSettings>();
        }
    
        public byte PatternID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ZonesSettings> ZonesSettings { get; set; }
    }
}
