//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUser
    {
        public LoginUser()
        {
            this.UserAccount = new HashSet<UserAccount>();
        }
    
        public long UserID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public long AdminUserID { get; set; }
        public string AdminUserGUID { get; set; }
        public string LastTruncToken { get; set; }
        public int UIFormatID { get; set; }
    
        public virtual LoginUser_UIFormat LoginUser_UIFormat { get; set; }
        public virtual ICollection<UserAccount> UserAccount { get; set; }
    }
}
