//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUser_UIFormat
    {
        public LoginUser_UIFormat()
        {
            this.LoginUser = new HashSet<LoginUser>();
        }
    
        public int UIFormatID { get; set; }
        public string LongDatePattern { get; set; }
        public string ShortDatePattern { get; set; }
        public string ShortTimePattern { get; set; }
        public string LongTimePattern { get; set; }
        public string CultureCode { get; set; }
        public string YearMonthPattern { get; set; }
        public string DisplayName { get; set; }
        public bool IsRightToLeft { get; set; }
        public bool IsDefault { get; set; }
        public byte StartDayOfWeek { get; set; }
    
        public virtual ICollection<LoginUser> LoginUser { get; set; }
    }
}
