//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoginUser> LoginUser { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<GlobalizationZone> GlobalizationZone { get; set; }
        public virtual DbSet<LoginUser_UIFormat> LoginUser_UIFormat { get; set; }
        public virtual DbSet<SharedSite> SharedSite { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<AlertSetting> AlertSetting { get; set; }
        public virtual DbSet<DeviceMain> DeviceMain { get; set; }
        public virtual DbSet<KeyValue> KeyValue { get; set; }
        public virtual DbSet<listClockView> listClockView { get; set; }
        public virtual DbSet<listCycleSoakPattern> listCycleSoakPattern { get; set; }
        public virtual DbSet<listModel> listModel { get; set; }
        public virtual DbSet<listOperationSequence> listOperationSequence { get; set; }
        public virtual DbSet<listStatus> listStatus { get; set; }
        public virtual DbSet<listTempratureUnit> listTempratureUnit { get; set; }
        public virtual DbSet<listType> listType { get; set; }
        public virtual DbSet<ZoneMain> ZoneMain { get; set; }
        public virtual DbSet<ConfigManager> ConfigManager { get; set; }
        public virtual DbSet<Device_DisplaySettings> Device_DisplaySettings { get; set; }
        public virtual DbSet<ZoneMain1> ZoneMain1 { get; set; }
        public virtual DbSet<ZonesSettings> ZonesSettings { get; set; }
        public virtual DbSet<EraSetting> EraSetting { get; set; }
        public virtual DbSet<linkEra2Session> linkEra2Session { get; set; }
        public virtual DbSet<listSessionRestrictionType> listSessionRestrictionType { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<SessionDaySetting> SessionDaySetting { get; set; }
        public virtual DbSet<SessionSetting> SessionSetting { get; set; }
        public virtual DbSet<Site> Site { get; set; }
        public virtual DbSet<listWaterSavingAlgorithm> listWaterSavingAlgorithm { get; set; }
        public virtual DbSet<WaterSavingAlgorithm_P1> WaterSavingAlgorithm_P1 { get; set; }
    }
}
