//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedSite
    {
        public long SiteID { get; set; }
        public System.DateTime ShareDate { get; set; }
        public Nullable<System.DateTime> ShareApproveDate { get; set; }
        public long ParentProjectID { get; set; }
        public bool IsPending { get; set; }
        public long ShareUserID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Site Site { get; set; }
    }
}
