//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.SharedSite = new HashSet<SharedSite>();
            this.DeviceMain = new HashSet<DeviceMain>();
            this.Site1 = new HashSet<Site>();
        }
    
        public string Name { get; set; }
        public long SiteID { get; set; }
        public Nullable<long> ParentSiteID { get; set; }
        public string MapCenter_Latitude { get; set; }
        public string MapCenter_Longitude { get; set; }
        public Nullable<byte> MapCenter_Zoom { get; set; }
        public string MapCenter_Mode { get; set; }
        public Nullable<long> EraID { get; set; }
        public Nullable<byte> WaterSavingAlgorithmID { get; set; }
        public int DefaultTimeZoneID { get; set; }
    
        public virtual GlobalizationZone GlobalizationZone { get; set; }
        public virtual ICollection<SharedSite> SharedSite { get; set; }
        public virtual ICollection<DeviceMain> DeviceMain { get; set; }
        public virtual EraSetting EraSetting { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<Site> Site1 { get; set; }
        public virtual Site Site2 { get; set; }
        public virtual listWaterSavingAlgorithm listWaterSavingAlgorithm { get; set; }
        public virtual WaterSavingAlgorithm_P1 WaterSavingAlgorithm_P1 { get; set; }
    }
}
