//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneMain
    {
        public long ZoneID { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public bool IsEnabled { get; set; }
        public long DeviceID { get; set; }
    
        public virtual ZoneMain1 ZoneMain1 { get; set; }
    }
}
